/**
 * The parts of dev-ap.mjs that only compute: no files, processes or network, so
 * packages/orocommerce/test/dev-ap-lib.test.mjs can call them directly.
 */
import { createHash } from 'node:crypto';
import { resolve as resolvePath } from 'node:path';

/** Read by dev-ap.mjs to pick the Activepieces checkout. Never copied into .env.dev. */
export const SOURCE_KEYS = ['DEV_AP_REPO', 'DEV_AP_REF'];

/** The checkout folder for upstream Activepieces at .ap-pin, the source when neither key is set. */
export const DEFAULT_FOLDER = '.ap-dev';

export const GENERATED_HEADER =
  '# Generated by npm run dev:ap on every run from the committed .env.dev and .env.dev.local. ' +
  'Edit .env.dev.local, not this file.';

/** A full commit sha, the only form of commit accepted in DEV_AP_REF, .ap-pin and a marker file. */
export const FULL_SHA = /^[0-9a-f]{40}$/;

/**
 * The reason a ref is refused, or null. A full sha passes. A name has to be one git would accept
 * (`git check-ref-format --allow-onelevel`, written out here so that it needs no git), and three
 * forms git itself accepts are refused too: ":" and a leading "+" make a refspec, which would
 * rewrite the checkout's own refs, and a leading "-" would be read as an option.
 */
export function refProblem(ref) {
  if (FULL_SHA.test(ref)) return null;
  if (ref.startsWith('-')) return 'starts with "-", which git would read as an option';
  if (ref.startsWith('+') || ref.includes(':')) {
    return 'is a refspec (a leading "+" or a ":"), not a commit, tag or branch name';
  }
  if (ref === '' || ref === '@') return 'is not a commit, tag or branch name';
  // eslint-disable-next-line no-control-regex
  if (/[\x00-\x20\x7f~^?*[\\]/.test(ref)) {
    return 'has a character git does not allow in a ref name (a space, control character, or one ' +
      'of ~ ^ ? * [ \\)';
  }
  if (ref.includes('..') || ref.includes('@{') || ref.includes('//')) {
    return 'has "..", "@{" or "//", which git does not allow in a ref name';
  }
  if (ref.startsWith('/') || ref.endsWith('/') || ref.endsWith('.')) {
    return 'starts or ends with "/", or ends with ".", which git does not allow in a ref name';
  }
  if (ref.split('/').some((part) => part.startsWith('.') || part.endsWith('.lock'))) {
    return 'has a path component starting with "." or ending with ".lock", which git does not allow';
  }
  return null;
}

/**
 * One KEY=value per line; blank lines and # comments are skipped. Anything else is refused rather
 * than guessed at, because a line this could not read would otherwise go missing without a word.
 */
export function parseLocalEnv(text) {
  const settings = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line);
    if (!match) throw new Error(`.env.dev.local: expected KEY=value, got:\n  ${raw}`);
    settings.push([match[1], match[2]]);
  }
  return settings;
}

/** The last value for the key, as dotenv would read it, without the quotes .env files allow. */
function lastValue(settings, key) {
  const found = settings.filter(([k]) => k === key).pop();
  if (!found) return '';
  const value = found[1].trim();
  const quoted = /^(["'])(.*)\1$/.exec(value);
  return quoted ? quoted[2] : value;
}

export function sourceFolder(repo, ref) {
  const hash = createHash('sha256').update(`${repo}\n${ref}`).digest('hex');
  return `${DEFAULT_FOLDER}-${hash.slice(0, 12)}`;
}

/**
 * True when git would read the repository as a local path rather than a URL: anything without a
 * colon (so no scheme and no `host:path`), or starting with `/`, `./` or `../`.
 */
export function isLocalRepoPath(repo) {
  return !repo.includes(':') || /^(\/|\.\.?\/)/.test(repo);
}

/**
 * Neither key: upstream at .ap-pin in .ap-dev/, as before these keys existed, and so is upstream
 * named explicitly at the pin. Any other source gets a folder of its own, so switching sources never
 * reuses another one's install or dev database. A local path is resolved against `root` (the
 * repository root) first, since git would otherwise read a relative one from inside the checkout
 * folder; the folder name, the marker and every git call then use the absolute path.
 */
export function resolveSource(settings, upstream, pin, root) {
  const repo = lastValue(settings, 'DEV_AP_REPO');
  const ref = lastValue(settings, 'DEV_AP_REF');
  // Both reach git as positional arguments, where a leading "-" would be read as an option.
  for (const [key, value] of [
    ['DEV_AP_REPO', repo],
    ['DEV_AP_REF', ref],
  ]) {
    if (value.startsWith('-')) {
      throw new Error(
        `.env.dev.local: ${key} starts with "-", which git would read as an option, not as a ` +
          'repository or a ref. Remove it.'
      );
    }
  }
  if (repo && !ref) {
    throw new Error(
      '.env.dev.local sets DEV_AP_REPO but not DEV_AP_REF.\n' +
        'Add DEV_AP_REF with the commit, tag or branch to check out from that repository, or remove ' +
        'DEV_AP_REPO to run upstream Activepieces at .ap-pin.'
    );
  }
  if (ref) {
    const problem = refProblem(ref);
    if (problem) {
      throw new Error(
        `.env.dev.local: DEV_AP_REF ${problem}. Use a commit (the full 40-character sha), a tag ` +
          'or a branch name.'
      );
    }
  }
  let sourceRepo = repo || upstream;
  if (repo && isLocalRepoPath(repo)) sourceRepo = resolvePath(root, repo);
  if (!ref || (sourceRepo === upstream && ref === pin)) {
    return { isDefault: true, repo: upstream, ref: null, folder: DEFAULT_FOLDER };
  }
  // The URL is printed, kept in the checkout's git config and in its marker file. Over http(s),
  // anything before "@" in the authority is a credential, a token as the user name included.
  if (/^https?:\/\/[^/]*@/i.test(sourceRepo)) {
    throw new Error(
      '.env.dev.local: DEV_AP_REPO has a user name, password or token in the URL. Remove it: over ' +
        'https, git takes your credentials from a credential helper, or use an SSH URL. This script ' +
        'never stores one.'
    );
  }
  return { isDefault: false, repo: sourceRepo, ref, folder: sourceFolder(sourceRepo, ref) };
}

export function setEnvLine(text, key, value) {
  const line = `${key}=${value}`;
  // Every line for the key, not only the first: dotenv keeps the last one it reads, so a
  // duplicate further down would otherwise win silently. A function as the replacement, so a `$`
  // in the value is written as it is.
  const pattern = new RegExp(`^${key}=.*$`, 'gm');
  if (text.match(pattern)) return text.replace(pattern, () => line);
  return `${text}${text.endsWith('\n') || text === '' ? '' : '\n'}${line}\n`;
}

/**
 * .env.dev, rebuilt from scratch on every run so that .env.dev.local only has to hold overrides:
 * the checkout's committed file, then the script's own settings, then .env.dev.local on top. A line
 * deleted from .env.dev.local therefore brings the committed value back on the next run.
 * .env.dev.local cannot set the script's own keys, which are returned as `ignored`, and its source
 * keys are dropped because they mean nothing to Activepieces.
 */
export function buildEnvDev(committed, local, own) {
  const ownKeys = own.map(([key]) => key);
  let text = committed;
  for (const [key, value] of own) text = setEnvLine(text, key, value);
  const applied = new Set();
  const ignored = new Set();
  for (const [key, value] of local) {
    if (SOURCE_KEYS.includes(key)) continue;
    if (ownKeys.includes(key)) {
      ignored.add(key);
      continue;
    }
    text = setEnvLine(text, key, value);
    applied.add(key);
  }
  return { text: `${GENERATED_HEADER}\n${text}`, applied: [...applied], ignored: [...ignored] };
}

/** The marker a checkout other than the default carries, or null unless all three fields are sound. */
export function validMarker(marker) {
  if (!marker || typeof marker !== 'object') return null;
  const { repo, ref, commit } = marker;
  if (typeof repo !== 'string' || typeof ref !== 'string' || typeof commit !== 'string') return null;
  if (!FULL_SHA.test(commit)) return null;
  return { repo, ref, commit };
}

/** KEY=value lines as dotenv reads them: the last line for a key wins, anything else is skipped. */
function envValues(text) {
  const values = new Map();
  for (const raw of text.split(/\r?\n/)) {
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(raw.trim());
    if (match) values.set(match[1], match[2]);
  }
  return values;
}

/**
 * The keys whose value in `existing` is not the committed one, apart from `ignore`: what a .env.dev
 * edited by hand would lose when it is rebuilt. Names only, since the values may be secrets.
 */
export function changedEnvKeys(existing, committed, ignore = []) {
  const before = envValues(committed);
  const after = envValues(existing);
  const keys = new Set([...before.keys(), ...after.keys()]);
  return [...keys].filter((key) => !ignore.includes(key) && before.get(key) !== after.get(key)).sort();
}

/**
 * Folders named `name` under `within` that hold a package.json, other than `keep`, from git's
 * tracked paths (always `/`-separated). Activepieces looks for pieces under packages/pieces only,
 * and finds a dev piece by its folder name, so a second one there would be built or served instead
 * of the copy.
 */
export function strayPieceFolders(paths, name, keep, within) {
  const suffix = `${name}/package.json`;
  const folders = paths
    .filter((path) => path.startsWith(`${within}/`))
    .filter((path) => path.endsWith(`/${suffix}`))
    .map((path) => path.slice(0, -'/package.json'.length))
    .filter((folder) => folder !== keep);
  return [...new Set(folders)];
}
