/**
 * The parts of dev-ap.mjs that only compute: no files, processes or network, so
 * packages/orocommerce/test/dev-ap-lib.test.mjs can call them directly.
 */
import { createHash } from 'node:crypto';

/** Read by dev-ap.mjs to pick the Activepieces checkout. Never copied into .env.dev. */
export const SOURCE_KEYS = ['DEV_AP_REPO', 'DEV_AP_REF'];

/** The checkout folder for upstream Activepieces at .ap-pin, the source when neither key is set. */
export const DEFAULT_FOLDER = '.ap-dev';

export const GENERATED_HEADER =
  '# Generated by npm run dev:ap on every run from the committed .env.dev and .env.dev.local. ' +
  'Edit .env.dev.local, not this file.';

/**
 * One KEY=value per line; blank lines and # comments are skipped. Anything else is refused rather
 * than guessed at, because a line this could not read would otherwise go missing without a word.
 */
export function parseLocalEnv(text) {
  const settings = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const match = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line);
    if (!match) throw new Error(`.env.dev.local: expected KEY=value, got:\n  ${raw}`);
    settings.push([match[1], match[2]]);
  }
  return settings;
}

/** The last value for the key, as dotenv would read it, without the quotes .env files allow. */
function lastValue(settings, key) {
  const found = settings.filter(([k]) => k === key).pop();
  if (!found) return '';
  const value = found[1].trim();
  const quoted = /^(["'])(.*)\1$/.exec(value);
  return quoted ? quoted[2] : value;
}

export function sourceFolder(repo, ref) {
  const hash = createHash('sha256').update(`${repo}\n${ref}`).digest('hex');
  return `${DEFAULT_FOLDER}-${hash.slice(0, 12)}`;
}

/**
 * Neither key: upstream at .ap-pin in .ap-dev/, as before these keys existed. Any other source gets
 * a folder of its own, so switching sources never reuses another one's install or dev database.
 */
export function resolveSource(settings, upstream) {
  const repo = lastValue(settings, 'DEV_AP_REPO');
  const ref = lastValue(settings, 'DEV_AP_REF');
  if (repo && !ref) {
    throw new Error(
      '.env.dev.local sets DEV_AP_REPO but not DEV_AP_REF.\n' +
        'Add DEV_AP_REF with the commit, tag or branch to check out from that repository, or remove ' +
        'DEV_AP_REPO to run upstream Activepieces at .ap-pin.'
    );
  }
  if (!ref) return { isDefault: true, repo: upstream, ref: null, folder: DEFAULT_FOLDER };
  const sourceRepo = repo || upstream;
  // The URL is printed, kept in the checkout's git config and in its marker file.
  if (/^[a-z][a-z0-9+.-]*:\/\/[^/@]*:[^/@]*@/i.test(sourceRepo)) {
    throw new Error(
      '.env.dev.local: DEV_AP_REPO has a password or token in the URL. Remove it: git uses your own ' +
        'credentials (an SSH key or a credential helper), and this script never stores one.'
    );
  }
  return { isDefault: false, repo: sourceRepo, ref, folder: sourceFolder(sourceRepo, ref) };
}

export function setEnvLine(text, key, value) {
  const line = `${key}=${value}`;
  // Every line for the key, not only the first: dotenv keeps the last one it reads, so a
  // duplicate further down would otherwise win silently. A function as the replacement, so a `$`
  // in the value is written as it is.
  const pattern = new RegExp(`^${key}=.*$`, 'gm');
  if (text.match(pattern)) return text.replace(pattern, () => line);
  return `${text}${text.endsWith('\n') || text === '' ? '' : '\n'}${line}\n`;
}

/**
 * .env.dev, rebuilt from scratch on every run so that .env.dev.local only has to hold overrides:
 * the checkout's committed file, then the script's own settings, then .env.dev.local on top. A line
 * deleted from .env.dev.local therefore brings the committed value back on the next run.
 * .env.dev.local cannot set the script's own keys, which are returned as `ignored`, and its source
 * keys are dropped because they mean nothing to Activepieces.
 */
export function buildEnvDev(committed, local, own) {
  const ownKeys = own.map(([key]) => key);
  let text = committed;
  for (const [key, value] of own) text = setEnvLine(text, key, value);
  const applied = new Set();
  const ignored = new Set();
  for (const [key, value] of local) {
    if (SOURCE_KEYS.includes(key)) continue;
    if (ownKeys.includes(key)) {
      ignored.add(key);
      continue;
    }
    text = setEnvLine(text, key, value);
    applied.add(key);
  }
  return { text: `${GENERATED_HEADER}\n${text}`, applied: [...applied], ignored: [...ignored] };
}

/**
 * Folders named `name` that hold a package.json, other than `keep`, from git's tracked paths (always
 * `/`-separated). Activepieces finds a dev piece by its folder name, so a second one would be built
 * or served instead of the copy.
 */
export function strayPieceFolders(paths, name, keep) {
  const suffix = `${name}/package.json`;
  const folders = paths
    .filter((path) => path === suffix || path.endsWith(`/${suffix}`))
    .map((path) => path.slice(0, -'/package.json'.length))
    .filter((folder) => folder !== keep);
  return [...new Set(folders)];
}
